modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "neuro21"
version = "${version}"
displayName = "Neuro21"
authors = "JimenezLi"
description = '''
Mod for AI VTuber Neuro-sama; 9+10=21!
'''
logoFile = "logo.png"

[[dependencies.neuro21]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neuro21]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.neuro21]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"